stages:
    - build
    - push
    - deploy
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    TAG_LATEST: gasnownow/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: gasnownow/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

build:
    stage: build    
    image: docker:20.10.13-alpine3.15
    services:
         - docker:20.10.13-dind-alpine3.15
    script:
         - echo $CI_COMMIT_SHORT_SHA
         - docker build -t $TAG_COMMIT .
         - docker save $TAG_COMMIT > gasnownow.tar
    artifacts:
         expire_in: 1 week
         paths:
             - gasnownow.tar

push:
    stage: push
    image: docker:20.10.13-alpine3.15
    services:
        - docker:20.10.13-dind-alpine3.15
    script:
        - echo $CI_COMMIT_SHORT_SHA
        #- docker login registry.gitlab.com
        #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        #- docker login registry.gitlab.com -u michaelalexbincom -p QftQM2WDFqzswpPxf1jL
        #- docker push $TAG_COMMIT
        #- docker push $TAG_LATEST
